services:
  redis:
    image: redis:8.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: "redis-server --save 20 1 --loglevel warning --requirepass testone1234!"
    volumes:
      - redis:/data
  nproxy:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - REDIS_URL=redis:6379
      - REDIS_PASSWORD=testone1234!
      - NAVIDROME_URL=http://host.docker.internal:4533
volumes:
  redis:
    driver: local
